# CrewX Quickstart

👋 Welcome! This project was generated by `npx crewx-quickstart`.

You now have a fully configured CrewX workspace with a **custom `@quickstart` agent**.

## Try it in two commands

```bash
crewx q "@quickstart hi"
crewx x "@quickstart build a plan for this repo"
```

> Tip: `q` is an alias for `query`, and `x` is an alias for `execute`.

## What was created

| File | Purpose |
| ---- | ------- |
| `crewx.yaml` | Custom agent definition + inline docs for the quickstart assistant |
| `.env.slack` | Placeholder Slack credentials (fill these in before running the bot) |
| `start-slack.sh` | One-liner script to launch the Slack bot with the quickstart agent |
| `README.md` | This guide – safe to edit or replace |

## Next steps

1. **Personalise the agent**  
   Open `crewx.yaml` and adjust the `instructions` block or add documents.

2. **Connect Slack (optional)**  
   - Fill in `.env.slack`  
   - Run `./start-slack.sh`  
   - Talk to `@quickstart` inside your workspace threads.

3. **Explore multi-agent workflows**  
   Add more agents to `crewx.yaml`, then run:  
   ```bash
   crewx q "@quickstart @claude brainstorm a roadmap"
   ```

4. **Share feedback**  
   Let us know what you build! https://github.com/sowonlabs/crewx

Happy building! 🚀
